cors:
  originPatterns: http://localhost:3000,http://localhost:8080
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/app?serverTimezone=UTC
      username: root
      password: root
  jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
  flyway:
    locations: classpath:db/migration

springdoc:
  paths-to-match: /api/v1/**
  swagger-ui:
    use-root-path: true