name: Continuous Integration

on:
  push:
    branches: 
      - main
      - development
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          
      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
          
      - name: Build Application JAR
        working-directory: /app
        run: mvn clean package
      
      - name: Docker Compose build
        working-directory: /app
        run: docker compose build 

      - name: Push To Docker Hub Container Registry
        run: 
          docker tag ${{secrets.DOCKER_USERNAME}}/app:latest ${{secrets.DOCKER_USERNAME}}/app:${{ github.run_id }}
          docker push ${{secrets.DOCKER_USERNAME}}/app:${{ github.run_id }}
          docker push ${{secrets.DOCKER_USERNAME}}/app:latest
